name: raptee_iot_gui
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^26.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  infinite_scroll_pagination: ^4.0.0
  http: ^1.0.0
  intl: ^0.19.0
  flutter_tabler_icons: ^1.43.0
  google_fonts: ^6.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  go_router: ^13.0.0
  get_it: ^7.6.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true



  assets:
    - assets/images/error_illustration.png
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
